//! Writes `~/.config/mitos/home.conf` — a small, plain `key = value`
//! projection of a handful of settings that `mitos-gui` (the compositor)
//! and `mitos-file-manager` watch directly via inotify for live preview.
//!
//! This is deliberately a *different, simpler* format from
//! `settings::persistence`'s own on-disk store: no type tags, no
//! `__version__` header, just the exact keys those two programs expect.
//! It's a one-way projection — mitos-settings is the source of truth;
//! nothing reads this file back in.
//!
//! No IPC or D-Bus round trip is needed to push a change out: writing the
//! file *is* the notification, since both watchers pick it up via
//! inotify. See docs/home-conf.md for the full contract.

use crate::settings::manager::SettingsManager;
use std::fs;
use std::io::{self, Write};
use std::path::Path;

/// Every settings key whose current value feeds into home.conf. Checked by
/// `SettingsManager::set` after a successful write (see `sync_if_relevant`),
/// so home.conf regenerates automatically whenever any one of these
/// changes — the caller never has to remember to do it.
const RELEVANT_KEYS: &[&str] = &[
    "theme.mode",
    "appearance.accent_color",
    "appearance.glass_opacity",
    "appearance.panel_radius",
    "wallpaper.desktop_path",
    "appearance.top_bar_enabled",
    "appearance.top_bar_height",
    "appearance.dock_enabled",
    "appearance.dock_height",
    "appearance.launcher_enabled",
    "applications.file_manager_show_hidden",
    "applications.file_manager_thumbnails_enabled",
    "applications.file_manager_thumbnail_max_mb",
];

/// Called by `SettingsManager::set` after every successful write. Cheap
/// when it's a no-op (a plain slice membership check), and only actually
/// touches disk if `key` is one home.conf cares about.
pub fn sync_if_relevant(key: &str, manager: &SettingsManager, path: &Path) {
    if !RELEVANT_KEYS.contains(&key) {
        return;
    }
    if let Err(e) = write_home_conf(manager, path) {
        eprintln!("mitos-settings: could not update {}: {e}", path.display());
    }
}

/// Writes home.conf from whatever the manager's current values are,
/// regardless of what (if anything) just changed. Called once when a
/// "real" `SettingsManager` (one pointed at the actual shared config
/// dir, not a test's throwaway one) is loaded, so the file exists and is
/// correct even before any setting is changed in this run.
pub fn write_initial(manager: &SettingsManager, path: &Path) {
    if let Err(e) = write_home_conf(manager, path) {
        eprintln!("mitos-settings: could not write initial {}: {e}", path.display());
    }
}

fn write_home_conf(manager: &SettingsManager, path: &Path) -> io::Result<()> {
    let str_of = |key: &str| manager.get(key).ok().and_then(|v| v.as_str()).unwrap_or_default().to_string();
    let bool_of = |key: &str| manager.get(key).ok().and_then(|v| v.as_bool()).unwrap_or(false);
    let int_of = |key: &str| manager.get(key).ok().and_then(|v| v.as_int()).unwrap_or(0);
    let float_of = |key: &str| manager.get(key).ok().and_then(|v| v.as_float()).unwrap_or(0.0);

    // theme.mode is "light" | "dark" | "system" internally; home.conf's
    // contract only understands the first two. There's no real desktop
    // "system theme" signal to resolve against here (that's a
    // session/compositor concern), so "system" falls back to "dark" --
    // revisit if mitos-gui ends up wanting to resolve this itself instead.
    let theme_mode = match str_of("theme.mode").as_str() {
        "light" => "light",
        _ => "dark",
    };

    let mut out = String::new();
    out.push_str("# Generated by mitos-settings. Do not edit by hand --\n");
    out.push_str("# changes here are overwritten the next time a relevant\n");
    out.push_str("# setting changes. Edit via `mitos-settings set <key> <value>`.\n\n");

    out.push_str("# --- Visual Theme ---\n");
    out.push_str(&format!("theme_mode = {theme_mode}\n"));
    out.push_str(&format!("accent_color = {}\n", str_of("appearance.accent_color")));
    out.push_str(&format!("glass_opacity = {}\n", float_of("appearance.glass_opacity")));
    out.push_str(&format!("panel_radius = {}\n", float_of("appearance.panel_radius")));

    out.push_str("\n# --- Wallpaper ---\n");
    out.push_str(&format!("wallpaper = {}\n", str_of("wallpaper.desktop_path")));

    out.push_str("\n# --- Shell Layout ---\n");
    out.push_str(&format!("top_bar = {}\n", bool_of("appearance.top_bar_enabled")));
    out.push_str(&format!("top_bar_height = {}\n", float_of("appearance.top_bar_height")));
    out.push_str(&format!("dock = {}\n", bool_of("appearance.dock_enabled")));
    out.push_str(&format!("dock_height = {}\n", float_of("appearance.dock_height")));
    out.push_str(&format!("launcher = {}\n", bool_of("appearance.launcher_enabled")));

    out.push_str("\n# --- File Manager Preferences ---\n");
    out.push_str(&format!("show_hidden_files = {}\n", bool_of("applications.file_manager_show_hidden")));
    out.push_str(&format!("enable_thumbnails = {}\n", bool_of("applications.file_manager_thumbnails_enabled")));
    out.push_str(&format!("thumbnail_max_mb = {}\n", int_of("applications.file_manager_thumbnail_max_mb")));

    write_atomically(path, &out)
}

/// Always ensures the parent directory exists first (`~/.config/mitos/`
/// won't exist on a fresh install), then writes via a temp-file-plus-rename
/// so a watcher never observes a half-written file.
fn write_atomically(path: &Path, contents: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("tmp");
    {
        let mut f = fs::File::create(&tmp)?;
        f.write_all(contents.as_bytes())?;
        f.sync_all()?;
    }
    fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::manager::{test_support::isolated_manager, Mode};
    use crate::settings::value::Value;

    fn temp_home_conf_path(label: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("mitos-home-conf-test-{label}-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join("home.conf")
    }

    #[test]
    fn write_initial_produces_every_expected_key() {
        let (manager, manager_dir) = isolated_manager(Mode::Standalone);
        let path = temp_home_conf_path("initial");

        write_initial(&manager, &path);
        let contents = fs::read_to_string(&path).unwrap();

        for expected_key in [
            "theme_mode", "accent_color", "glass_opacity", "panel_radius", "wallpaper", "top_bar",
            "top_bar_height", "dock", "dock_height", "launcher", "show_hidden_files", "enable_thumbnails",
            "thumbnail_max_mb",
        ] {
            assert!(
                contents.lines().any(|l| l.trim_start().starts_with(&format!("{expected_key} ="))),
                "missing '{expected_key}' in generated home.conf:\n{contents}"
            );
        }

        std::fs::remove_dir_all(path.parent().unwrap()).ok();
        std::fs::remove_dir_all(manager_dir).ok();
    }

    #[test]
    fn sync_if_relevant_reflects_a_changed_accent_color() {
        let (mut manager, manager_dir) = isolated_manager(Mode::Standalone);
        let path = temp_home_conf_path("accent");

        manager.set("appearance.accent_color", Value::Str("#ff0000".into())).unwrap();
        sync_if_relevant("appearance.accent_color", &manager, &path);

        let contents = fs::read_to_string(&path).unwrap();
        assert!(contents.contains("accent_color = #ff0000"));

        std::fs::remove_dir_all(path.parent().unwrap()).ok();
        std::fs::remove_dir_all(manager_dir).ok();
    }

    #[test]
    fn sync_if_relevant_is_a_no_op_for_unrelated_keys() {
        let (manager, manager_dir) = isolated_manager(Mode::Standalone);
        let path = temp_home_conf_path("unrelated");

        sync_if_relevant("sound.volume", &manager, &path);
        assert!(!path.exists(), "home.conf should not be created for a key it doesn't care about");

        std::fs::remove_dir_all(manager_dir).ok();
        let _ = fs::remove_dir_all(path.parent().unwrap());
    }

    #[test]
    fn system_theme_mode_resolves_to_dark_in_home_conf() {
        let (manager, manager_dir) = isolated_manager(Mode::Standalone);
        let path = temp_home_conf_path("system-theme");

        // Default theme.mode is "system" -- confirm the projection resolves
        // it rather than writing a value home.conf's contract disallows.
        write_initial(&manager, &path);
        let contents = fs::read_to_string(&path).unwrap();
        assert!(contents.contains("theme_mode = dark"));

        std::fs::remove_dir_all(path.parent().unwrap()).ok();
        std::fs::remove_dir_all(manager_dir).ok();
    }
}
